"""LLM backend abstraction layer — provider-neutral interface.

§7.2 authentication three backends, §7.3 multi-provider abstraction and
stage-wise model routing.

Defines the ``LLMBackend`` protocol that all backends must implement, along
with shared message and response data structures.  Orchestration logic is
provider-agnostic.
"""

from __future__ import annotations

import abc
from collections.abc import Iterator
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Message types
# ---------------------------------------------------------------------------


class Role(StrEnum):
    """Conversation participant role."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ContentBlock(BaseModel):
    """A single content block (text or tool result)."""

    type: str = "text"
    text: str | None = None
    tool_use_id: str | None = None
    content: str | None = None

    model_config = {"extra": "allow"}


class Message(BaseModel):
    """LLM conversation message (OpenAI format compatible)."""

    role: Role
    content: str | list[ContentBlock]
    name: str | None = None
    # tool_call_id links a TOOL-role message back to the originating tool call.
    # Required by OpenAI/Anthropic APIs for multi-tool-call responses; None for
    # non-tool messages.
    tool_call_id: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to a dictionary for direct use with provider APIs."""
        d: dict[str, Any] = {"role": self.role.value}
        if isinstance(self.content, str):
            d["content"] = self.content
        else:
            d["content"] = [b.model_dump(exclude_none=True) for b in self.content]
        if self.name:
            d["name"] = self.name
        if self.tool_call_id is not None:
            d["tool_call_id"] = self.tool_call_id
        return d


# ---------------------------------------------------------------------------
# Tool call data structures (linked with tools.py)
# ---------------------------------------------------------------------------


class ToolCall(BaseModel):
    """A tool call requested by the LLM."""

    id: str
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Usage & cost metadata
# ---------------------------------------------------------------------------


class UsageStats(BaseModel):
    """LLM response token usage and estimated cost."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    # USD estimate (populated only when the backend knows this)
    estimated_cost_usd: float | None = None
    # Latency in seconds
    latency_sec: float | None = None


# ---------------------------------------------------------------------------
# Shared response type
# ---------------------------------------------------------------------------


class LLMResponse(BaseModel):
    """Unified response data structure returned by all backends."""

    # Text response generated by the model (None when only tool calls are present)
    content: str | None = None
    # Tool calls requested by the model
    tool_calls: list[ToolCall] = Field(default_factory=list)
    # Reason the response stopped ("end_turn" | "tool_use" | "max_tokens" | "stop_sequence")
    stop_reason: str = "end_turn"
    # Usage statistics (for budget tracking)
    usage: UsageStats = Field(default_factory=UsageStats)
    # Raw provider response (for debugging and provenance)
    raw: Any | None = None
    # Backend-specific non-secret transport metadata. This is intentionally
    # separate from ``content`` so integrity gates audit only the model answer.
    metadata: dict[str, Any] = Field(default_factory=dict)
    # Model identifier used
    model: str | None = None


# ---------------------------------------------------------------------------
# Pipeline stage — stage-wise model routing (§7.3)
# ---------------------------------------------------------------------------


class PipelineStage(StrEnum):
    """Pipeline stage — corresponds 1:1 to keys in config.toml [routing].

    Planning and deep reasoning use high-capability models; build, summarise,
    and compress use cheaper models; figure vision critic uses a vision model.
    """

    PLAN = "plan"  # planning / deep reasoning → high-capability model
    BUILD = "build"  # build / generate → mid-tier model
    SUMMARIZE = "summarize"  # summarise / compress → cheap model
    VISION_CRITIC = "vision_critic"  # figure vision critic → vision model
    DEFAULT = "default"  # fallback when no stage is specified


# Stage → default model mapping (hardcoded defaults used when config.toml is absent)
_DEFAULT_ROUTING: dict[PipelineStage, str] = {
    PipelineStage.PLAN: "claude-opus-4-7",
    PipelineStage.BUILD: "claude-sonnet-4-6",
    PipelineStage.SUMMARIZE: "claude-haiku-4-5-20251001",
    PipelineStage.VISION_CRITIC: "claude-opus-4-7",
    PipelineStage.DEFAULT: "claude-opus-4-7",
}


class ModelRouter:
    """Pipeline stage → model identifier mapping router.

    Reads the ``[routing]`` section from ``config.toml`` to determine the
    model for each stage.  Falls back to ``_DEFAULT_ROUTING`` when the section
    or a specific stage is absent.
    """

    def __init__(self, routing_config: dict[str, str] | None = None) -> None:
        """Initialise the router.

        Args:
            routing_config: ``config.toml`` [routing] section dictionary.
                            Only hardcoded defaults are used when None.
        """
        self._table: dict[PipelineStage, str] = dict(_DEFAULT_ROUTING)
        if routing_config:
            for key, model in routing_config.items():
                try:
                    stage = PipelineStage(key)
                    self._table[stage] = model
                except ValueError:
                    # Unknown stage — silently ignored (forward compatibility)
                    pass

    def model_for(self, stage: PipelineStage | str) -> str:
        """Return the model identifier for the given stage.

        Args:
            stage: ``PipelineStage`` member or stage name string.

        Returns:
            Model identifier string.  Returns the ``DEFAULT`` model for
            unregistered stages.
        """
        if isinstance(stage, str):
            try:
                stage = PipelineStage(stage)
            except ValueError:
                return self._table[PipelineStage.DEFAULT]
        return self._table.get(stage, self._table[PipelineStage.DEFAULT])

    @classmethod
    def default(cls) -> ModelRouter:
        """Return a default router instance (hardcoded defaults only, no config)."""
        return cls(routing_config=None)


# ---------------------------------------------------------------------------
# Abstract LLM backend interface
# ---------------------------------------------------------------------------


class LLMBackend(abc.ABC):
    """Provider-neutral LLM interface.

    Three concrete implementations inherit from this class:
    - ``backends.api.APIBackend``  — LiteLLM direct API
    - ``backends.delegated_cli.DelegatedCLIBackend``  — subprocess CLI
    - ``backends.local.LocalBackend``  — Ollama local model

    All methods return ``LLMResponse`` or produce a streaming iterator.
    """

    # Default model identifier used by this backend
    default_model: str = "claude-opus-4-7"

    @abc.abstractmethod
    def complete(
        self,
        messages: list[Message],
        *,
        model: str | None = None,
        tools: list[dict[str, Any]] | None = None,
        temperature: float | None = None,
        max_tokens: int = 4096,
        stop: list[str] | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        """Perform a non-streaming completion request and return ``LLMResponse``.

        Args:
            messages: Conversation message list (system · user · assistant order).
            model: Model identifier to use.  Uses ``self.default_model`` if None.
            tools: Tool definition list in JSON Schema format.
            temperature: Sampling temperature (may be ignored by some providers).
            max_tokens: Maximum number of tokens to generate.
            stop: Stop sequence list.
            **kwargs: Backend-specific additional arguments.

        Returns:
            Unified response data structure ``LLMResponse``.
        """

    @abc.abstractmethod
    def stream(
        self,
        messages: list[Message],
        *,
        model: str | None = None,
        tools: list[dict[str, Any]] | None = None,
        temperature: float | None = None,
        max_tokens: int = 4096,
        stop: list[str] | None = None,
        **kwargs: Any,
    ) -> Iterator[str]:
        """Streaming completion request — yields text chunks in order.

        Args:
            messages: Conversation message list.
            model: Model identifier to use.
            tools: Tool definition list in JSON Schema format.
            temperature: Sampling temperature.
            max_tokens: Maximum number of tokens to generate.
            stop: Stop sequence list.
            **kwargs: Backend-specific additional arguments.

        Yields:
            Text chunk strings.
        """

    @abc.abstractmethod
    def health_check(self) -> bool:
        """Check the backend connection status.

        Returns:
            True if the connection is available; False otherwise.
        """

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    def _resolve_model(self, model: str | None) -> str:
        """Return ``self.default_model`` when model is None."""
        return model if model is not None else self.default_model
