"""tests/integrity/test_persona_disclosure.py — Comprehensive violation tests for all seven safeguards.

Blocks each safeguard violation case:
  ① Missing disclosure label
  ② First-person attribution
  ③ Fabricated citation (citation without DOI)
  ④ Out-of-scope assertion
  ⑤ Fabricated expertise (outside corpus)
  ⑥ Opted-out author
  ⑦ Missing AI reviewer label
"""

from __future__ import annotations

import pytest

from maglab.reviewer.disclosure import (
    DisclosureViolation,
    PersonaDisclosureError,
    PersonaGuard,
    build_disclosure_label,
    check_ai_reviewer_label,
    check_disclosure_label,
    check_expertise_fabrication,
    check_fabricated_citations,
    check_first_person,
    check_optout,
    check_scope,
    clear_optout_registry,
    is_opted_out,
    register_optout,
    unregister_optout,
    violations_to_honesty_gate,
)

# ---------------------------------------------------------------------------
# Common helpers
# ---------------------------------------------------------------------------

VALID_DISCLOSURE_TEXT = (
    "[AI Reviewer — Corpus Model] "
    "This review was generated by an AI Reviewer modeled from 15 public papers by Prof. Smith. "
    "This is not Prof. Smith's actual opinion or endorsement. "
    "For manuscript preparation feedback only."
)


def _guard(author_id: str = "author_test") -> PersonaGuard:
    return PersonaGuard(
        author_id=author_id,
        author_name="Prof. Test",
        verified_dois={"10.1103/valid.001", "10.1103/valid.002"},
    )


# ---------------------------------------------------------------------------
# Safeguard ①: Missing disclosure label
# ---------------------------------------------------------------------------


class TestSafeguard1DisclosureLabel:
    """Safeguard ①: Missing disclosure label → blocked."""

    def test_missing_disclosure_label_detected(self):
        text = "This paper presents interesting results. The spin Hall angle was clearly measured."
        violations = check_disclosure_label(text)
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.MISSING_DISCLOSURE_LABEL

    def test_valid_disclosure_label_passes(self):
        violations = check_disclosure_label(VALID_DISCLOSURE_TEXT)
        assert violations == []

    def test_persona_guard_blocks_missing_label(self):
        """PersonaGuard blocks text without the disclosure label."""
        guard = _guard()
        bad_text = "This is a novel paper."  # No label
        with pytest.raises(PersonaDisclosureError) as exc_info:
            guard.guard(bad_text)
        violations = exc_info.value.violations
        kinds = [v.violation for v in violations]
        assert DisclosureViolation.MISSING_DISCLOSURE_LABEL in kinds

    def test_build_disclosure_label_format(self):
        label = build_disclosure_label("Prof. Kim", 20)
        assert "AI Reviewer" in label
        assert "20 public papers" in label
        assert "actual opinion" in label or "endorsement" in label

    def test_add_disclosure_auto_prepend(self):
        """add_disclosure automatically prepends the label."""
        guard = _guard()
        text = "A novel paper."
        result = guard.add_disclosure(text, paper_count=10)
        assert "AI Reviewer" in result
        # Must not add duplicate labels
        result2 = guard.add_disclosure(result, paper_count=10)
        assert result2.count("AI Reviewer") == result.count("AI Reviewer")


# ---------------------------------------------------------------------------
# Safeguard ②: First-person attribution forbidden
# ---------------------------------------------------------------------------


class TestSafeguard2FirstPerson:
    """Safeguard ②: First-person attribution pattern → blocked."""

    @pytest.mark.parametrize(
        "bad_text",
        [
            "I calculated that this effect is clear.",
            "I discovered that this material shows SOT.",
            "my analysis shows the novelty is insufficient.",
            "I found that the spin Hall angle is large.",
            "my calculation shows the effect is significant.",
            "I have measured the magnetization.",
        ],
    )
    def test_first_person_detected(self, bad_text: str):
        violations = check_first_person(bad_text)
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.FIRST_PERSON_ATTRIBUTION

    def test_third_person_passes(self):
        """Third-person inferential form passes."""
        text = "Based on this corpus, the author has emphasized the spin Hall effect."
        violations = check_first_person(text)
        assert violations == []

    def test_persona_guard_blocks_first_person(self):
        guard = _guard()
        bad_text = VALID_DISCLOSURE_TEXT + "\nI calculated that this paper is novel."
        with pytest.raises(PersonaDisclosureError) as exc_info:
            guard.guard(bad_text)
        kinds = [v.violation for v in exc_info.value.violations]
        assert DisclosureViolation.FIRST_PERSON_ATTRIBUTION in kinds


# ---------------------------------------------------------------------------
# Safeguard ③: Fabricated citations forbidden
# ---------------------------------------------------------------------------


class TestSafeguard3FabricatedCitation:
    """Safeguard ③: Citation without DOI → fabricated citation blocked."""

    def test_citation_without_doi_detected(self):
        """A citation with [1] or et al. but no DOI may be fabricated."""
        text = "This effect was reported in Smith et al. (2020)."
        violations = check_fabricated_citations(text)
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.FABRICATED_CITATION

    def test_citation_with_doi_passes(self):
        """A citation with a DOI passes."""
        text = "This effect is confirmed in the literature (DOI: 10.1103/PhysRevLett.100.096401)."
        violations = check_fabricated_citations(text)
        assert violations == []

    def test_unverified_doi_blocked(self):
        """A DOI not in the verified DOI set is blocked."""
        text = "This cites the paper (DOI: 10.1103/fake.999)."
        verified = {"10.1103/valid.001"}
        violations = check_fabricated_citations(text, verified_dois=verified)
        assert any("fake.999" in v.excerpt for v in violations)

    def test_verified_doi_passes(self):
        text = "The result refers to DOI: 10.1103/valid.001."
        verified = {"10.1103/valid.001"}
        violations = check_fabricated_citations(text, verified_dois=verified)
        assert violations == []

    def test_persona_guard_blocks_fabricated_citation(self):
        guard = PersonaGuard(
            author_id="author_test",
            author_name="Prof. Test",
            verified_dois={"10.1103/valid.001"},
        )
        bad_text = VALID_DISCLOSURE_TEXT + "\nMeasured in Smith et al. (2020)."
        with pytest.raises(PersonaDisclosureError) as exc_info:
            guard.guard(bad_text)
        kinds = [v.violation for v in exc_info.value.violations]
        assert DisclosureViolation.FABRICATED_CITATION in kinds


# ---------------------------------------------------------------------------
# Safeguard ④: Scope limit
# ---------------------------------------------------------------------------


class TestSafeguard4ScopeLimit:
    """Safeguard ④: Scope limited to publicly published positions."""

    def test_out_of_scope_marker_detected(self):
        text = (
            VALID_DISCLOSURE_TEXT
            + "\nIn this field, it is generally accepted that this method is correct."
        )
        violations = check_scope(text)
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.OUT_OF_SCOPE_OPINION

    def test_normal_opinion_passes(self):
        text = VALID_DISCLOSURE_TEXT + "\nThis author's papers emphasize SOT measurements."
        violations = check_scope(text)
        assert violations == []


# ---------------------------------------------------------------------------
# Safeguard ⑤: Fabricated expertise outside the corpus forbidden
# ---------------------------------------------------------------------------


class TestSafeguard5FabricatedExpertise:
    """Safeguard ⑤: Fabricated expertise outside the corpus forbidden."""

    @pytest.mark.parametrize(
        "bad_text",
        [
            "unpublished data shows this is correct.",
            "my unpublished measurements show this value is correct.",
            "I personally calculated that this effect is observed.",
        ],
    )
    def test_expertise_fabrication_detected(self, bad_text: str):
        violations = check_expertise_fabrication(bad_text)
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.FABRICATED_EXPERTISE

    def test_corpus_based_opinion_passes(self):
        text = "The spin Hall angle was reported in this author's public papers."
        violations = check_expertise_fabrication(text)
        assert violations == []


# ---------------------------------------------------------------------------
# Safeguard ⑥: Opt-out registry
# ---------------------------------------------------------------------------


class TestSafeguard6OptOut:
    """Safeguard ⑥: Opt-out registry."""

    def setup_method(self):
        clear_optout_registry()

    def teardown_method(self):
        clear_optout_registry()

    def test_register_optout_blocks_persona(self):
        register_optout("blocked_researcher")
        violations = check_optout("blocked_researcher")
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.OPTED_OUT_AUTHOR

    def test_non_opted_out_author_passes(self):
        violations = check_optout("normal_author")
        assert violations == []

    def test_optout_case_insensitive(self):
        register_optout("BlockedAuthor")
        violations = check_optout("blockedauthor")
        assert len(violations) >= 1

    def test_unregister_optout(self):
        register_optout("temp_author")
        unregister_optout("temp_author")
        assert not is_opted_out("temp_author")

    def test_persona_guard_blocks_opted_out(self):
        register_optout("opted_out_prof")
        guard = PersonaGuard(author_id="opted_out_prof", author_name="Opted Out")
        eligibility = guard.check_author_eligibility()
        assert len(eligibility) >= 1
        assert eligibility[0].violation == DisclosureViolation.OPTED_OUT_AUTHOR

    def test_clear_optout_registry(self):
        register_optout("a1")
        register_optout("a2")
        clear_optout_registry()
        assert not is_opted_out("a1")
        assert not is_opted_out("a2")


# ---------------------------------------------------------------------------
# Safeguard ⑦: AI reviewer label
# ---------------------------------------------------------------------------


class TestSafeguard7AIReviewerLabel:
    """Safeguard ⑦: 'AI Reviewer' or 'Corpus Model' labeling required."""

    def test_missing_ai_reviewer_label(self):
        text = "The novelty of this paper is sufficient."  # No AI Reviewer label
        violations = check_ai_reviewer_label(text)
        assert len(violations) >= 1
        assert violations[0].violation == DisclosureViolation.MISSING_AI_REVIEWER_LABEL

    def test_ai_reviewer_present_passes(self):
        text = "This review was generated by an AI Reviewer (corpus model)."
        violations = check_ai_reviewer_label(text)
        assert violations == []

    def test_corpus_model_label_passes(self):
        text = "Corpus model-based review: the novelty is high."
        violations = check_ai_reviewer_label(text)
        assert violations == []

    def test_persona_guard_blocks_missing_ai_label(self):
        guard = _guard()
        # Has some disclosure text but missing AI reviewer naming
        bad_text = (
            "A reviewer modeled from public papers (not their actual opinion).\n"
            "This paper is interesting."
        )
        result = guard.guard(bad_text, raise_on_violation=False)
        # Should fail because AI Reviewer label is absent
        if not result.passed:
            kinds = [v.violation for v in result.violations]
            assert DisclosureViolation.MISSING_AI_REVIEWER_LABEL in kinds


# ---------------------------------------------------------------------------
# PersonaGuard integration tests
# ---------------------------------------------------------------------------


class TestPersonaGuardIntegration:
    """PersonaGuard integration tests for all seven safeguards."""

    def setup_method(self):
        clear_optout_registry()

    def test_fully_compliant_text_passes(self):
        """Text that complies with all seven safeguards passes."""
        guard = _guard()
        compliant_text = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 10 public papers by Prof. Test. "
            "This is not Prof. Test's actual opinion or endorsement.\n\n"
            "This author's public papers report the spin Hall effect "
            "(DOI: 10.1103/valid.001)."
        )
        result = guard.guard(compliant_text, raise_on_violation=False)
        assert result.passed, result.summary()

    def test_multiple_violations_all_detected(self):
        """Simultaneously violating multiple safeguards detects all of them."""
        guard = _guard()
        multi_bad = (
            "I calculated that this paper is good. "  # ②
            "Cites Smith et al. (2019). "  # ③ (no DOI)
        )
        # Missing disclosure label → ①, ⑦
        with pytest.raises(PersonaDisclosureError) as exc_info:
            guard.guard(multi_bad)
        violations = exc_info.value.violations
        kinds = {v.violation for v in violations}
        # At minimum: missing disclosure label, first-person attribution, fabricated citation
        assert len(kinds) >= 2

    def test_violations_to_honesty_gate_conversion(self):
        """Convert DisclosureViolationRecord to HonestyGate Violation."""
        guard = _guard()
        bad_text = "I calculated this."
        result = guard.guard(bad_text, raise_on_violation=False)
        hg_violations = violations_to_honesty_gate(result.violations)
        assert isinstance(hg_violations, list)


# ---------------------------------------------------------------------------
# Regression tests — F-02: DOI case normalization
# ---------------------------------------------------------------------------


class TestF02DOICaseNormalization:
    """Regression tests for F-02: DOI comparison must be case-insensitive.

    Previously, a mixed-case DOI in review text (e.g. from the paper itself)
    was falsely flagged as FABRICATED_CITATION even when the lowercase version
    existed in the verified set.
    """

    def test_mixed_case_doi_not_flagged_when_verified_lowercase(self):
        """Mixed-case DOI in text matches lowercase entry in verified_dois."""
        text = "See DOI: 10.1103/PhysRevLett.132.156801 for details."
        # verified_dois stores lowercase (as connectors normalise on ingest)
        verified = {"10.1103/physrevlett.132.156801"}
        violations = check_fabricated_citations(text, verified_dois=verified)
        fabricated = [
            v for v in violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == [], f"Mixed-case DOI falsely flagged as fabricated: {fabricated}"

    def test_uppercase_doi_not_flagged_when_verified_lowercase(self):
        """Fully uppercased DOI still matches lowercase entry."""
        text = "DOI: 10.1103/PHYSREVLETT.132.156801"
        verified = {"10.1103/physrevlett.132.156801"}
        violations = check_fabricated_citations(text, verified_dois=verified)
        fabricated = [
            v for v in violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == []

    def test_truly_unverified_doi_still_flagged(self):
        """A DOI genuinely absent from the verified set is still flagged."""
        text = "DOI: 10.1234/fake.999"
        verified = {"10.1103/physrevlett.132.156801"}
        violations = check_fabricated_citations(text, verified_dois=verified)
        fabricated = [
            v for v in violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert len(fabricated) >= 1

    def test_persona_guard_mixed_case_doi_passes(self):
        """PersonaGuard does not block a mixed-case verified DOI."""
        guard = PersonaGuard(
            author_id="author_x",
            author_name="Prof. X",
            verified_dois={"10.1103/physrevlett.132.156801"},
        )
        compliant = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. X. "
            "This is not Prof. X's actual opinion or endorsement.\n\n"
            "The result is supported by DOI: 10.1103/PhysRevLett.132.156801."
        )
        result = guard.guard(compliant, raise_on_violation=False)
        fabricated = [
            v for v in result.violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == [], result.summary()


# ---------------------------------------------------------------------------
# Regression tests — F-06: arXiv IDs validated when verified_arxivs provided
# ---------------------------------------------------------------------------


class TestF06ArXivValidation:
    """Regression tests for F-06: fabricated arXiv IDs must be caught."""

    def test_unverified_arxiv_flagged(self):
        """An arXiv ID not in verified_arxivs is flagged as FABRICATED_CITATION."""
        text = "[AI Reviewer] See arXiv:2305.99999 for background."
        violations = check_fabricated_citations(
            text,
            verified_dois={"10.1103/valid.001"},
            verified_arxivs={"2305.00001"},
        )
        fabricated = [
            v for v in violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert len(fabricated) >= 1
        assert any("2305.99999" in v.excerpt for v in fabricated)

    def test_verified_arxiv_passes(self):
        """An arXiv ID present in verified_arxivs is NOT flagged."""
        text = "[AI Reviewer] See arXiv:2305.00001 for details."
        violations = check_fabricated_citations(
            text,
            verified_dois=set(),
            verified_arxivs={"2305.00001"},
        )
        fabricated = [
            v for v in violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == []

    def test_arxiv_without_verified_set_not_flagged(self):
        """When verified_arxivs is None, arXiv IDs are not individually validated."""
        text = "[AI Reviewer] Reference: arXiv:2305.99999."
        violations = check_fabricated_citations(text, verified_dois=None, verified_arxivs=None)
        # No DOI-only citation pattern check triggers — arXiv ID counts as ref
        fabricated = [
            v for v in violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == []


# ---------------------------------------------------------------------------
# Regression tests — N-01: fabricated arXiv IDs flagged via PersonaGuard.guard()
# ---------------------------------------------------------------------------


class TestN01ArXivValidationViaPersonaGuard:
    """Regression tests for N-01: PersonaGuard.guard() must propagate verified_arxivs
    to check_fabricated_citations() so fabricated arXiv IDs are caught in production paths.

    Previously PersonaGuard.__init__ did not accept/store verified_arxivs, so
    arXiv:9999.99999 would silently pass through guard() even when a real verified
    set was available.
    """

    def test_fabricated_arxiv_blocked_through_guard(self):
        """A fabricated arXiv ID is caught when PersonaGuard is given verified_arxivs."""
        guard = PersonaGuard(
            author_id="author_arxiv_test",
            author_name="Prof. ArXiv",
            verified_dois=set(),
            verified_arxivs={"2305.12345"},
        )
        # Text that would have silently passed before N-01 fix.
        bad_text = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. ArXiv. "
            "This is not Prof. ArXiv's actual opinion or endorsement.\n\n"
            "See arXiv:9999.99999 for the foundational result."
        )
        result = guard.guard(bad_text, raise_on_violation=False)
        fabricated = [
            v for v in result.violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert len(fabricated) >= 1, (
            "Fabricated arXiv ID arXiv:9999.99999 was not caught by PersonaGuard.guard(). "
            "N-01 fix may be missing."
        )
        assert any("9999.99999" in v.excerpt for v in fabricated)

    def test_verified_arxiv_passes_through_guard(self):
        """A verified arXiv ID does NOT raise a violation via PersonaGuard."""
        guard = PersonaGuard(
            author_id="author_arxiv_test",
            author_name="Prof. ArXiv",
            verified_dois=set(),
            verified_arxivs={"2305.12345"},
        )
        good_text = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. ArXiv. "
            "This is not Prof. ArXiv's actual opinion or endorsement.\n\n"
            "See arXiv:2305.12345 for the foundational result."
        )
        result = guard.guard(good_text, raise_on_violation=False)
        fabricated = [
            v for v in result.violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == [], (
            f"Verified arXiv ID arXiv:2305.12345 was incorrectly flagged: {fabricated}"
        )

    def test_no_verified_arxivs_does_not_flag_any_arxiv(self):
        """When verified_arxivs is not provided, arXiv IDs are not individually validated."""
        guard = PersonaGuard(
            author_id="author_arxiv_test",
            author_name="Prof. ArXiv",
            verified_dois=set(),
            # verified_arxivs intentionally omitted (defaults to None)
        )
        text = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. ArXiv. "
            "This is not Prof. ArXiv's actual opinion or endorsement.\n\n"
            "See arXiv:9999.99999 for background."
        )
        result = guard.guard(text, raise_on_violation=False)
        fabricated = [
            v for v in result.violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == [], (
            "ArXiv ID should not be flagged when verified_arxivs was not supplied to PersonaGuard."
        )

    def test_persona_spec_verified_arxivs_propagated(self):
        """PersonaSpec.verified_arxivs is propagated through ReviewPanel._review_single
        so a fabricated arXiv ID in the review is caught end-to-end."""
        from maglab.reviewer.corpus_rag import CorpusChunk, CorpusRAG
        from maglab.reviewer.panel import PersonaSpec, ReviewPanel

        rag = CorpusRAG()
        rag.add_chunk(
            CorpusChunk(
                chunk_id="chunk_001",
                author_id="arxiv_author",
                doi="10.1234/test.001",
                title="A Real Paper",
                text="spin Hall effect measurement",
            )
        )
        persona = PersonaSpec(
            author_id="arxiv_author",
            author_name="Prof. ArXiv Author",
            paper_count=1,
            verified_dois={"10.1234/test.001"},
            verified_arxivs={"2305.12345"},
        )

        fabricated_arxiv_text = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 1 public papers by Prof. ArXiv Author. "
            "This is not Prof. ArXiv Author's actual opinion or endorsement.\n\n"
            "See arXiv:9999.99999 for a key result."
        )

        def fake_llm(p: PersonaSpec, manuscript: str, rag_results: list, rubric: object) -> str:
            return fabricated_arxiv_text

        panel = ReviewPanel(
            personas=[persona],
            corpus_rag=rag,
            llm_review_fn=fake_llm,
        )
        result = panel.review("Test manuscript.", raise_on_disclosure_violation=False)
        assert len(result.reviews) == 1
        pr = result.reviews[0]
        # disclosure_passed should be False because arXiv:9999.99999 is not in verified_arxivs
        assert not pr.disclosure_passed, (
            "ReviewPanel did not flag fabricated arXiv:9999.99999 even though "
            "PersonaSpec.verified_arxivs={'2305.12345'} was provided. "
            "PersonaSpec.verified_arxivs propagation may be missing."
        )


# ---------------------------------------------------------------------------
# Regression tests — F-01: PersonaSpec.verified_dois defaults to None
# ---------------------------------------------------------------------------


class TestF01VerifiedDoisDefaultNone:
    """Regression tests for F-01: PersonaSpec.verified_dois and verified_arxivs
    must default to None, not set().

    Semantics:
      - None  → skip per-ID whitelist check (lenient default when RAG not populated)
      - set() → enforce whitelist; empty set means every cited ID is unverified
      - {doi} → only the listed IDs are allowed
    """

    def test_default_persona_spec_does_not_flag_real_doi(self) -> None:
        """A review citing a real DOI must NOT be flagged when PersonaSpec uses its
        default (verified_dois=None). Before F-01, verified_dois=set() caused every
        cited 10.xxx DOI to be flagged as FABRICATED_CITATION.
        """
        # PersonaSpec with all defaults — verified_dois=None, verified_arxivs=None
        from maglab.reviewer.disclosure import DisclosureViolation, PersonaGuard

        guard = PersonaGuard(
            author_id="f01_author",
            author_name="Prof. F01",
            # verified_dois intentionally omitted → None (default in PersonaGuard)
        )
        review_with_doi = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. F01. "
            "This is not Prof. F01's actual opinion or endorsement.\n\n"
            "The spin Hall effect is documented in DOI: 10.1103/PhysRevLett.100.096401."
        )
        result = guard.guard(review_with_doi, raise_on_violation=False)
        fabricated = [
            v for v in result.violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert fabricated == [], (
            f"Real DOI was falsely flagged as fabricated when verified_dois=None: {fabricated}. "
            "F-01: PersonaSpec.verified_dois must default to None, not set()."
        )

    def test_populated_verified_dois_rejects_unlisted_doi(self) -> None:
        """When verified_dois is a populated set, an unlisted DOI is rejected."""
        from maglab.reviewer.disclosure import DisclosureViolation, PersonaGuard

        guard = PersonaGuard(
            author_id="f01_author",
            author_name="Prof. F01",
            verified_dois={"10.1103/physrevlett.100.096401"},  # only this DOI allowed
        )
        review_with_unlisted_doi = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. F01. "
            "This is not Prof. F01's actual opinion or endorsement.\n\n"
            "See DOI: 10.9999/unlisted.paper for context."
        )
        result = guard.guard(review_with_unlisted_doi, raise_on_violation=False)
        fabricated = [
            v for v in result.violations if v.violation == DisclosureViolation.FABRICATED_CITATION
        ]
        assert len(fabricated) >= 1, (
            "Unlisted DOI was not rejected when verified_dois was a populated set."
        )
        assert any("unlisted.paper" in v.excerpt for v in fabricated)

    def test_persona_spec_default_verified_dois_is_none(self) -> None:
        """PersonaSpec() default verified_dois must be None, not set()."""
        from maglab.reviewer.panel import PersonaSpec

        spec = PersonaSpec(author_id="test_author")
        assert spec.verified_dois is None, (
            f"PersonaSpec.verified_dois default must be None, got {spec.verified_dois!r}. "
            "F-01: change default from field(default_factory=set) to None."
        )
        assert spec.verified_arxivs is None, (
            f"PersonaSpec.verified_arxivs default must be None, got {spec.verified_arxivs!r}. "
            "F-01: change default from field(default_factory=set) to None."
        )

    def test_none_verified_dois_via_panel_does_not_flag_doi(self) -> None:
        """End-to-end: PersonaSpec with default verified_dois=None does not flag a
        review containing a real DOI, even through the full ReviewPanel path.
        """
        from maglab.reviewer.corpus_rag import CorpusChunk, CorpusRAG
        from maglab.reviewer.panel import PersonaSpec, ReviewPanel

        rag = CorpusRAG()
        rag.add_chunk(
            CorpusChunk(
                chunk_id="f01-chunk-001",
                author_id="f01_panel_author",
                doi="10.1103/physrevlett.100.096401",
                title="Spin Hall Paper",
                text="spin Hall effect measurement in Pt",
            )
        )

        # Default PersonaSpec — verified_dois=None, verified_arxivs=None
        persona = PersonaSpec(
            author_id="f01_panel_author",
            author_name="Prof. F01 Panel",
            paper_count=5,
            # Neither verified_dois nor verified_arxivs supplied
        )

        review_with_real_doi = (
            "[AI Reviewer — Corpus Model] "
            "This review was generated by an AI Reviewer modeled from 5 public papers by Prof. F01 Panel. "
            "This is not Prof. F01 Panel's actual opinion or endorsement.\n\n"
            "The spin Hall effect is documented in DOI: 10.1103/PhysRevLett.100.096401."
        )

        def fake_llm(p: PersonaSpec, manuscript: str, rag_results: list, rubric: object) -> str:
            return review_with_real_doi

        panel = ReviewPanel(
            personas=[persona],
            corpus_rag=rag,
            llm_review_fn=fake_llm,
        )
        result = panel.review("Test manuscript.", raise_on_disclosure_violation=False)
        pr = result.reviews[0]

        assert pr.disclosure_passed, (
            "ReviewPanel falsely blocked a valid review citing a real DOI when "
            "PersonaSpec uses default verified_dois=None. F-01 fix may be missing."
        )
