"""Unidirectional Spin Hall Magnetoresistance (USMR) EffectModel.

Fitting equation:
    ΔR / R_0 = ε·(j × M) · ẑ

where ε is the USMR coefficient (units: Ω·m² / A) and the longitudinal
resistance depends linearly on the current direction relative to the
magnetization.  In a Hall-bar geometry with current j∥x and M∥±y:

    ΔR_USMR / R_0 = ε·j_x · m_y

Experimental observable (two-current protocol or AC lock-in):
    R(+j) − R(−j) = 2 · ε · j · M_y / R_0

The asymmetry ratio A = [R(+j) − R(−j)] / 2R_0 = ε·j·m_y is fitted
against the current density j, yielding ε (or equivalently ξ_USMR = ε/ρ_xx).

Sources:
    Olejnik, K. et al.,
    Nat. Commun. 8, 15434 (2017).
    DOI: 10.1038/ncomms15434

    Avci, C. O. et al.,
    Nat. Phys. 11, 570 (2015).
    DOI: 10.1038/nphys3356

    Avci, C. O. et al.,
    Phys. Rev. B 92, 184415 (2015).
    DOI: 10.1103/PhysRevB.92.184415
"""

from __future__ import annotations

from typing import Any

import numpy as np

from maglab.analysis.effects.base import (
    EffectModel,
    FitResult,
    MeasurementConfig,
    ParamSpec,
)
from maglab.analysis.fit import run_fit


class USMREffect(EffectModel):
    """Unidirectional Spin Hall Magnetoresistance (USMR) EffectModel.

    USMR is a current-polarity-dependent magnetoresistance arising from the
    interaction between the spin accumulation generated by the spin Hall effect
    and the magnetization in an adjacent ferromagnet.  The signal is linear in
    both current density j and the magnetization projection m_y, making it
    distinct from ordinary AMR/SMR (which are quadratic in spin-orbit coupling).

    Physical picture (Avci et al. 2015):
        - HM/FM bilayer with current j∥x̂.
        - SHE generates σ_y spin accumulation at HM/FM interface.
        - If M∥ŷ the spin accumulation adds to / reduces M → ΔR depends on sign of j.
        - Measured as R(+j) − R(−j) ≡ 2·ΔR_USMR.

    Fitting model (linear):
        A(j) = ΔR_USMR(j) / (2 R_0) = ε · j

    where ε [Ω·m²/A or simply m²/A if R_0 normalized to 1] is the USMR
    coefficient and is extracted from the slope of the asymmetry vs. j sweep.

    For a fixed current density with magnetization angle dependence:
        A(φ) = ε · j₀ · sin(φ)

    where φ is the in-plane angle of M from x̂.

    Sources:
        Olejnik, K. et al., Nat. Commun. 8, 15434 (2017).
        DOI: 10.1038/ncomms15434
        Avci, C. O. et al., Nat. Phys. 11, 570 (2015).
        DOI: 10.1038/nphys3356
    """

    @property
    def name(self) -> str:
        return "usmr"

    @property
    def subfield(self) -> str:
        return "magnetotransport"

    @property
    def references(self) -> list[str]:
        return [
            "Olejnik, K. et al., Nat. Commun. 8, 15434 (2017). DOI: 10.1038/ncomms15434",
            "Avci, C. O. et al., Nat. Phys. 11, 570 (2015). DOI: 10.1038/nphys3356",
            "Avci, C. O. et al., Phys. Rev. B 92, 184415 (2015). DOI: 10.1103/PhysRevB.92.184415",
        ]

    @property
    def parameters(self) -> list[ParamSpec]:
        return [
            ParamSpec(
                name="epsilon",
                unit="m^2/A",
                lower=None,
                upper=None,
                description=(
                    "USMR coefficient ε: asymmetry ratio per unit current density. "
                    "A(j) = ε·j  [dimensionless / (A/m²)]."
                ),
            ),
            ParamSpec(
                name="offset",
                unit="dimensionless",
                lower=None,
                upper=None,
                description="Constant offset in asymmetry ratio (instrument drift / background).",
            ),
        ]

    @property
    def measurement_config(self) -> MeasurementConfig:
        return MeasurementConfig(
            geometry=(
                "HM/FM Hall bar. Longitudinal resistance measured at +j and −j. "
                "M saturated along ŷ (transverse) by an external field. "
                "Current j swept along x̂. "
                "Signal: A = [R(+j) − R(−j)] / (2 R_0)  [dimensionless]."
            ),
            tensor_rank=2,
            required_columns=("j", "A"),
            notes=(
                "j [A/m²]: current density sweep (can include positive and negative values). "
                "A [dimensionless]: antisymmetric resistance asymmetry ratio ΔR/(2R_0). "
                "Alternatively, supply (phi, A) for magnetization-angle dependence mode, "
                "where phi [rad] is the in-plane M angle and A = ε·j₀·sin(phi)."
            ),
        )

    @property
    def symmetry_constraints(self) -> dict[str, Any]:
        return {
            "usmr_allowed": True,
            "time_reversal_odd": True,
        }

    def forward(
        self,
        params: dict[str, float],
        geometry: dict[str, Any] | None = None,
    ) -> np.ndarray:
        """Compute USMR asymmetry ratio A = ε·j + offset.

        Two modes determined by ``geometry``:

        **Current-sweep mode** (default): x = j [A/m²]
            A(j) = ε · j + offset

        **Angle-sweep mode**: geometry must contain ``j_0`` and x = phi [rad]
            A(φ) = ε · j₀ · sin(φ) + offset

        Args:
            params: {"epsilon": float, "offset": float}.
            geometry: {
                "j": ndarray  [A/m²]  — or —
                "phi": ndarray [rad] + "j_0": float [A/m²]
            }.

        Returns:
            A array [dimensionless].
        """
        epsilon = params["epsilon"]
        offset = params["offset"]
        geo = geometry or {}

        if "phi" in geo:
            phi = np.asarray(geo["phi"])
            j_0 = float(geo.get("j_0", 1.0))
            return epsilon * j_0 * np.sin(phi) + offset
        else:
            j = np.asarray(geo.get("j", np.array([0.0])))
            return epsilon * j + offset

    def fit(
        self,
        data: dict[str, np.ndarray],
        geometry: dict[str, Any] | None = None,
    ) -> FitResult:
        """Fit USMR coefficient ε from asymmetry-ratio vs. current-density data.

        Supports two modes:
        - Current-sweep: data must contain "j" and "A" columns.
        - Angle-sweep: data must contain "phi" and "A" columns; geometry must
          provide "j_0" (fixed current density magnitude).

        Args:
            data: {"j": ndarray, "A": ndarray}  or  {"phi": ndarray, "A": ndarray}.
            geometry: {"j_0": float} for angle-sweep mode.

        Returns:
            FitResult with params {"epsilon", "offset"}.
        """
        A_data = data["A"]
        geo = geometry or {}

        if "phi" in data:
            # Angle-sweep mode: A(φ) = ε·j₀·sin(φ) + offset
            phi = data["phi"]
            j_0 = float(geo.get("j_0", 1.0))

            # Linear regression: A = (ε·j₀)·sin(φ) + offset
            X = np.column_stack([np.sin(phi), np.ones_like(phi)])
            try:
                coeffs = np.linalg.lstsq(X, A_data, rcond=None)[0]
                init = {"epsilon": float(coeffs[0]) / j_0, "offset": float(coeffs[1])}
            except Exception:
                init = {"epsilon": 1e-15, "offset": 0.0}

            _j_0 = j_0

            def model_fn(x: np.ndarray, epsilon: float, offset: float) -> np.ndarray:
                return epsilon * _j_0 * np.sin(x) + offset

            return run_fit(
                model_fn=model_fn,
                x_data=phi,
                y_data=A_data,
                param_specs=self.parameters,
                init_values=init,
                effect_name=self.name,
            )

        else:
            # Current-sweep mode: A(j) = ε·j + offset
            j = data["j"]

            # Linear regression: A = ε·j + offset
            X = np.column_stack([j, np.ones_like(j)])
            try:
                coeffs = np.linalg.lstsq(X, A_data, rcond=None)[0]
                init = {"epsilon": float(coeffs[0]), "offset": float(coeffs[1])}
            except Exception:
                init = {"epsilon": 1e-15, "offset": 0.0}

            def model_fn_j(x: np.ndarray, epsilon: float, offset: float) -> np.ndarray:
                return epsilon * x + offset

            return run_fit(
                model_fn=model_fn_j,
                x_data=j,
                y_data=A_data,
                param_specs=self.parameters,
                init_values=init,
                effect_name=self.name,
            )
