"""MuMax3 input generation and execution wrapper.

Design rationale: impl/02-P1-figure-sim.md T-P1-06.

Generates a MuMax3 .mx3 script from a ``ScaleSpec`` (micro) and
runs it via the local backend. Returns a clear error when the MuMax3
binary is not installed.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from maglab.sim.backends.local import run_mumax3
from maglab.sim.custodian import classify
from maglab.sim.parse import JobResult, parse_mumax3_table
from maglab.sim.spec import ScaleSpec, ScaleType


def _generate_mx3(spec: ScaleSpec) -> str:
    """Generate a MuMax3 .mx3 script text from a ScaleSpec (micro).

    Parameters:
        spec: Micromagnetic ScaleSpec.

    Returns:
        .mx3 script text.

    Raises:
        ValueError: If spec.scale != "micro" or material/geometry is absent.
    """
    if spec.scale != ScaleType.micro:
        raise ValueError(f"mumax3 wrapper only supports scale='micro'. Got: {spec.scale}")
    if spec.material is None or spec.geometry is None:
        raise ValueError("material and geometry parameters are required.")

    mat = spec.material
    geom = spec.geometry

    dx = geom.dx_nm * 1e-9
    dy = geom.dy_nm * 1e-9
    dz = geom.dz_nm * 1e-9

    pbc_flags: list[str] = []
    if geom.pbc_x:
        pbc_flags.append("PBC_x")
    if geom.pbc_y:
        pbc_flags.append("PBC_y")
    if geom.pbc_z:
        pbc_flags.append("PBC_z")

    lines: list[str] = [
        "// MuMax3 script — auto-generated by MagLab",
        f"// Label: {spec.label or 'untitled'}",
        "",
        "// Grid definition",
        f"SetGridSize({geom.nx}, {geom.ny}, {geom.nz})",
        f"SetCellSize({dx:.6e}, {dy:.6e}, {dz:.6e})",
    ]

    if pbc_flags:
        lines.append(f"// PBC: {', '.join(pbc_flags)}")

    lines += [
        "",
        "// Material parameters",
        f"Msat  = {mat.Ms_Am:.6e}",
        f"Aex   = {mat.A_Jm:.6e}",
        f"alpha = {mat.alpha:.6g}",
    ]

    if mat.K_Jm3 != 0.0:
        ax, ay, az = mat.K_axis
        lines += [
            f"Ku1   = {mat.K_Jm3:.6e}",
            f"anisU = Vector({ax:.6g}, {ay:.6g}, {az:.6g})",
        ]

    if mat.D_Jm2 != 0.0:
        lines.append(f"Dind  = {mat.D_Jm2:.6e}")

    # Initial magnetization
    mx, my, mz = spec.initial_m_dir
    if spec.initial_state == "random":
        lines += ["", "// Initial magnetization: random", "m = RandomMag()"]
    else:
        lines += [
            "",
            "// Initial magnetization",
            f"m = Uniform({mx:.6g}, {my:.6g}, {mz:.6g})",
        ]

    # External magnetic field
    if spec.field_sweep is not None:
        fs = spec.field_sweep
        hx0, hy0, hz0 = fs.H_start_Am
        hx1, hy1, hz1 = fs.H_end_Am
        n = fs.n_steps
        lines += [
            "",
            "// External field sweep",
            f"// H: ({hx0:.4e},{hy0:.4e},{hz0:.4e}) → ({hx1:.4e},{hy1:.4e},{hz1:.4e}), {n} steps",
            "// (Sweep loop implemented in a separate script — setting initial value here)",
            f"B_ext = Vector({hx0 * 1.25663706212e-6:.6e}, {hy0 * 1.25663706212e-6:.6e}, {hz0 * 1.25663706212e-6:.6e})",
        ]
    else:
        lines += [
            "",
            "// No external field",
            "B_ext = Vector(0, 0, 0)",
        ]

    # Relaxation or time evolution
    if spec.t_sim_ns > 0.0:
        lines += [
            "",
            "// Time evolution",
            "TableAdd(E_total)",
            "TableAdd(m)",
            "TableAutoSave(1e-12)",
            f"Run({spec.t_sim_ns:.6e}e-9)",
        ]
    else:
        lines += [
            "",
            "// Energy minimization",
            "TableAdd(E_total)",
            "TableAdd(m)",
            "Relax()",
        ]

    return "\n".join(lines) + "\n"


def generate_mx3_file(
    spec: ScaleSpec,
    output_dir: Path | str | None = None,
    filename: str = "sim.mx3",
) -> Path:
    """Generate a .mx3 file from a ScaleSpec and return its path.

    Parameters:
        spec: Micromagnetic ScaleSpec.
        output_dir: Output directory. Uses a temporary directory if None.
        filename: .mx3 filename.

    Returns:
        Path to the generated .mx3 file.
    """
    mx3_text = _generate_mx3(spec)

    if output_dir is None:
        tmp = Path(tempfile.mkdtemp(prefix="maglab_mumax3_"))
    else:
        tmp = Path(output_dir)
        tmp.mkdir(parents=True, exist_ok=True)

    script_path = tmp / filename
    script_path.write_text(mx3_text, encoding="utf-8")
    return script_path


def run(
    spec: ScaleSpec,
    output_dir: Path | str | None = None,
    timeout_s: float = 3600.0,
) -> JobResult:
    """Run a MuMax3 simulation from a ScaleSpec and return a JobResult.

    Returns an error JobResult when MuMax3 is not installed.

    Parameters:
        spec: Micromagnetic ScaleSpec.
        output_dir: Output directory. Uses a temporary directory if None.
        timeout_s: Timeout [s].

    Returns:
        JobResult.
    """
    script_path = generate_mx3_file(spec, output_dir)
    result = run_mumax3(script_path, timeout_s=timeout_s)

    returncode = int(result["returncode"])  # type: ignore[call-overload]
    stdout = str(result.get("stdout", ""))
    stderr = str(result.get("stderr", ""))
    elapsed_s = float(result.get("elapsed_s", 0.0))  # type: ignore[arg-type]

    # Classify error
    custodian = classify(returncode, stdout, stderr, engine="mumax3")

    if not custodian.ok:
        return JobResult(
            job_id=str(script_path.stem),
            engine="mumax3",
            converged=False,
            elapsed_s=elapsed_s,
            error_message=f"[{custodian.error_class}] {custodian.message} | Hint: {custodian.hint}",
            raw_stdout=stdout,
            raw_stderr=stderr,
        )

    # Parse output
    # MuMax3 writes table.txt inside the {script.out}/ directory
    out_dir = script_path.parent / (script_path.stem + ".out")
    table_path = out_dir / "table.txt"

    if table_path.exists():
        job_result = parse_mumax3_table(table_path, job_id=script_path.stem)
        job_result = job_result.model_copy(
            update={"elapsed_s": elapsed_s, "raw_stdout": stdout, "raw_stderr": stderr}
        )

        # Collect OVF file paths (reference only)
        ovf_paths = [str(p) for p in out_dir.glob("*.ovf")]
        job_result = job_result.model_copy(update={"ovf_paths": ovf_paths})
    else:
        job_result = JobResult(
            job_id=script_path.stem,
            engine="mumax3",
            converged=True,
            elapsed_s=elapsed_s,
            error_message="table.txt not found.",
            raw_stdout=stdout,
            raw_stderr=stderr,
        )

    return job_result
