"""OOMMF MIF input generation and execution wrapper.

Design rationale: impl/02-P1-figure-sim.md T-P1-07.

Generates an OOMMF MIF 2.1 input file from a ``ScaleSpec`` (micro) and
runs it via the local backend. OOMMF is CPU-only and is the primary
validation target on the Mac development environment.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from maglab.sim.backends.local import run_oommf
from maglab.sim.custodian import classify
from maglab.sim.parse import JobResult, parse_oommf_odt
from maglab.sim.spec import ScaleSpec, ScaleType


def _generate_mif2(spec: ScaleSpec) -> str:
    """Generate an OOMMF MIF 2.1 script text from a ScaleSpec (micro).

    OOMMF MIF 2.1 reference:
        https://math.nist.gov/oommf/doc/userguide/userguide/MIF_2.1.html

    Parameters:
        spec: Micromagnetic ScaleSpec.

    Returns:
        .mif script text.
    """
    if spec.scale != ScaleType.micro:
        raise ValueError(f"oommf wrapper only supports scale='micro'. Got: {spec.scale}")
    if spec.material is None or spec.geometry is None:
        raise ValueError("material and geometry parameters are required.")

    mat = spec.material
    geom = spec.geometry

    # Physical dimensions [m]
    lx = geom.nx * geom.dx_nm * 1e-9
    ly = geom.ny * geom.dy_nm * 1e-9
    lz = geom.nz * geom.dz_nm * 1e-9
    dx = geom.dx_nm * 1e-9
    dy = geom.dy_nm * 1e-9
    dz = geom.dz_nm * 1e-9

    # Initial magnetization direction
    mx0, my0, mz0 = spec.initial_m_dir

    # External field (μ₀·H [T])
    _mu_0 = 1.25663706212e-6
    if spec.field_sweep is not None:
        hx, hy, hz = spec.field_sweep.H_start_Am
        bx = hx * _mu_0
        by = hy * _mu_0
        bz = hz * _mu_0
    else:
        bx = by = bz = 0.0

    # Anisotropy axis
    ax, ay, az = mat.K_axis

    lines: list[str] = [
        "# MIF 2.1 — auto-generated by MagLab",
        f"# Label: {spec.label or 'untitled'}",
        "",
        "# Grid and geometry",
        "Specify Oxs_BoxAtlas:atlas {",
        f"  xrange {{0 {lx:.6e}}}",
        f"  yrange {{0 {ly:.6e}}}",
        f"  zrange {{0 {lz:.6e}}}",
        "}",
        "",
        "Specify Oxs_RectangularMesh:mesh {",
        "  method smdes",
        "  atlas :atlas",
        f"  xstepsize {dx:.6e}",
        f"  ystepsize {dy:.6e}",
        f"  zstepsize {dz:.6e}",
        "}",
        "",
        "# Exchange interaction",
        "Specify Oxs_UniformExchange {",
        f"  A {mat.A_Jm:.6e}",
        "}",
    ]

    # Magnetostatic interaction
    lines += [
        "",
        "# Magnetostatic interaction",
        "Specify Oxs_Demag {}",
    ]

    # Anisotropy
    if mat.K_Jm3 != 0.0:
        lines += [
            "",
            "# Uniaxial anisotropy",
            "Specify Oxs_UniaxialAnisotropy {",
            f"  K1 {mat.K_Jm3:.6e}",
            f"  axis {{{{ {ax:.6g} {ay:.6g} {az:.6g} }}}}",
            "}",
        ]

    # External field
    lines += [
        "",
        "# External magnetic field",
        "Specify Oxs_FixedZeeman {",
        f"  field {{ {{Oxs_UniformField {{ field {{{bx:.6e} {by:.6e} {bz:.6e}}} }} }} }}",
        "}",
    ]

    # Time integration (LLG)
    if spec.t_sim_ns > 0.0:
        lines += [
            "",
            "# Time integration — LLG",
            "Specify Oxs_RungeKuttaEvolve:evolver {",
            f"  alpha {mat.alpha:.6g}",
            f"  gamma_G {1.760859630e11:.6e}",
            "}",
            "",
            "Specify Oxs_TimeDriver {",
            "  evolver :evolver",
            f"  stopping_time {spec.t_sim_ns:.6e}e-9",
            "  mesh :mesh",
            f"  Ms {mat.Ms_Am:.6e}",
            f"  m0 {{ Oxs_UniformVectorField {{ norm 1 vector {{{mx0:.6g} {my0:.6g} {mz0:.6g}}} }} }}",
            "}",
        ]
    else:
        # Energy minimization (CG)
        lines += [
            "",
            "# Energy minimization — CG",
            "Specify Oxs_CGEvolve:evolver {}",
            "",
            "Specify Oxs_MinDriver {",
            "  evolver :evolver",
            "  stopping_mxHxm 0.01",
            "  mesh :mesh",
            f"  Ms {mat.Ms_Am:.6e}",
            f"  m0 {{ Oxs_UniformVectorField {{ norm 1 vector {{{mx0:.6g} {my0:.6g} {mz0:.6g}}} }} }}",
            "}",
        ]

    # Output configuration
    lines += [
        "",
        "# Output configuration",
        "Destination table mmArchive",
        "Destination mags mmArchive",
        "Schedule DataTable table Step 1",
        "Schedule Oxs_TimeDriver::Magnetization mags Step 1",
    ]

    return "\n".join(lines) + "\n"


def generate_mif_file(
    spec: ScaleSpec,
    output_dir: Path | str | None = None,
    filename: str = "sim.mif",
) -> Path:
    """Generate a .mif file from a ScaleSpec and return its path.

    Parameters:
        spec: Micromagnetic ScaleSpec.
        output_dir: Output directory. Uses a temporary directory if None.
        filename: .mif filename.

    Returns:
        Path to the generated .mif file.
    """
    mif_text = _generate_mif2(spec)

    if output_dir is None:
        tmp = Path(tempfile.mkdtemp(prefix="maglab_oommf_"))
    else:
        tmp = Path(output_dir)
        tmp.mkdir(parents=True, exist_ok=True)

    mif_path = tmp / filename
    mif_path.write_text(mif_text, encoding="utf-8")
    return mif_path


def run(
    spec: ScaleSpec,
    output_dir: Path | str | None = None,
    timeout_s: float = 3600.0,
) -> JobResult:
    """Run an OOMMF simulation from a ScaleSpec and return a JobResult.

    Returns an error JobResult when OOMMF is not installed.

    Parameters:
        spec: Micromagnetic ScaleSpec.
        output_dir: Output directory. Uses a temporary directory if None.
        timeout_s: Timeout [s].

    Returns:
        JobResult.
    """
    mif_path = generate_mif_file(spec, output_dir)
    result = run_oommf(mif_path, timeout_s=timeout_s)

    returncode = int(result["returncode"])  # type: ignore[call-overload]
    stdout = str(result.get("stdout", ""))
    stderr = str(result.get("stderr", ""))
    elapsed_s = float(result.get("elapsed_s", 0.0))  # type: ignore[arg-type]

    # Classify error
    custodian = classify(returncode, stdout, stderr, engine="oommf")

    if not custodian.ok:
        return JobResult(
            job_id=str(mif_path.stem),
            engine="oommf",
            converged=False,
            elapsed_s=elapsed_s,
            error_message=f"[{custodian.error_class}] {custodian.message} | Hint: {custodian.hint}",
            raw_stdout=stdout,
            raw_stderr=stderr,
        )

    # Parse ODT output
    odt_path = mif_path.parent / (mif_path.stem + ".odt")
    if not odt_path.exists():
        # OOMMF writes the .odt file in the working directory
        odt_candidates = list(mif_path.parent.glob("*.odt"))
        if odt_candidates:
            odt_path = odt_candidates[0]

    if odt_path.exists():
        job_result = parse_oommf_odt(odt_path, job_id=mif_path.stem)
        job_result = job_result.model_copy(
            update={"elapsed_s": elapsed_s, "raw_stdout": stdout, "raw_stderr": stderr}
        )
        # Collect OVF paths
        ovf_paths = [str(p) for p in mif_path.parent.glob("*.omf")]
        job_result = job_result.model_copy(update={"ovf_paths": ovf_paths})
    else:
        job_result = JobResult(
            job_id=mif_path.stem,
            engine="oommf",
            converged=True,
            elapsed_s=elapsed_s,
            error_message=".odt output file not found.",
            raw_stdout=stdout,
            raw_stderr=stderr,
        )

    return job_result
