"""LLM→SVG schematic renderer (§12.3-②, §12.4).

``SchematicRenderer`` renders the schematic panels of a ``FigureSpec`` as SVG
vectors. It searches the primitive library (``figure/primitives/``) using natural
language queries, assembles SVG from parametric combinations, and exports to PDF
via the Inkscape CLI (headless). Falls back to cairosvg when Inkscape is not
installed.

Core principles:
- There is no code path in this file that calls raster generative image models (§12.1).
- The LLM authors SVG code, but **on top of** primitives — combining and parameterizing them.
- All SVG output includes provenance comments.
"""

from __future__ import annotations

import contextlib
import logging
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from maglab.figure.primitives.spec import Primitive, PrimitiveRegistry
from maglab.figure.spec import PanelSpec

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Inkscape detection
# ---------------------------------------------------------------------------

_INKSCAPE_BIN: str | None = None


def _find_inkscape() -> str | None:
    """Detect the Inkscape binary path. Returns None if not installed."""
    global _INKSCAPE_BIN  # noqa: PLW0603
    if _INKSCAPE_BIN is not None:
        return _INKSCAPE_BIN
    candidate = shutil.which("inkscape")
    if candidate:
        try:
            result = subprocess.run(
                [candidate, "--version"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                _INKSCAPE_BIN = candidate
                log.info("Inkscape detected: %s", candidate)
                return _INKSCAPE_BIN
        except Exception:  # noqa: BLE001
            pass
    log.info("Inkscape not installed — using cairosvg fallback")
    return None


# ---------------------------------------------------------------------------
# SVG assembly helpers
# ---------------------------------------------------------------------------

_SVG_HEADER_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="{width}mm" height="{height}mm"
     viewBox="0 0 {vb_width} {vb_height}">
  <!-- Generated by MagLab schematic.py — {provenance} -->
"""

_SVG_FOOTER = "</svg>\n"


def _wrap_in_group(svg_content: str, x: float = 0, y: float = 0) -> str:
    """Wrap SVG elements in a ``<g>`` translation group."""
    return f'<g transform="translate({x}, {y})">\n{svg_content}\n</g>\n'


def _extract_svg_body(svg_string: str) -> str:
    """Extract the inner body from a complete SVG document (inside ``<svg>`` tags)."""
    # Extract interior of <svg ...>...</svg>
    match = re.search(r"<svg[^>]*>(.*)</svg>", svg_string, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    # Return as-is when no tag found
    return svg_string.strip()


def _build_placement_plan(
    primitives_with_params: list[tuple[Primitive, dict[str, Any]]],
    canvas_width: float = 200.0,
    canvas_height: float = 150.0,
) -> list[tuple[Primitive, dict[str, Any], float, float]]:
    """Build a placement plan for primitives (simple left-to-right layout).

    Parameters
    ----------
    primitives_with_params:
        List of (Primitive, params) pairs.
    canvas_width:
        Canvas width in SVG user units.
    canvas_height:
        Canvas height.

    Returns
    -------
    list[(Primitive, params, x, y)]
        List with placement coordinates added.
    """
    n = len(primitives_with_params)
    if n == 0:
        return []

    # Evenly distributed left-to-right placement
    col_width = canvas_width / n
    result: list[tuple[Primitive, dict[str, Any], float, float]] = []
    for i, (prim, params) in enumerate(primitives_with_params):
        x = i * col_width + col_width * 0.1
        y = canvas_height * 0.1
        result.append((prim, params, x, y))
    return result


def assemble_svg(
    primitives_with_params: list[tuple[Primitive, dict[str, Any]]],
    *,
    width_mm: float = 89.0,
    height_mm: float = 60.0,
    backend: str = "svg",
    style: str = "nature",
    provenance: str = "MagLab schematic.py",
) -> str:
    """Assemble a complete SVG document from a list of primitives.

    Parameters
    ----------
    primitives_with_params:
        List of (Primitive, params) pairs to render.
    width_mm:
        SVG width in mm.
    height_mm:
        SVG height in mm.
    backend:
        Render backend (``"svg"`` by default).
    style:
        Journal style key.
    provenance:
        Provenance comment string.

    Returns
    -------
    str
        Complete SVG XML string.
    """
    # Viewbox units = mm * 3.7795 (96 dpi px/mm)
    vb_w = width_mm * 3.7795
    vb_h = height_mm * 3.7795

    placement = _build_placement_plan(
        primitives_with_params,
        canvas_width=vb_w,
        canvas_height=vb_h,
    )

    body_parts: list[str] = []
    for prim, params, x, y in placement:
        try:
            rendered = prim.render(params, backend=backend, style=style)
        except Exception as exc:  # noqa: BLE001
            log.warning("Primitive '%s' render error: %s", prim.name, exc)
            rendered = f"<!-- render error: {prim.name} -->"
        inner = _extract_svg_body(rendered)
        body_parts.append(_wrap_in_group(inner, x=x, y=y))

    body = "\n".join(body_parts)
    # XML/SVG comments must not contain "--".  Replace any occurrence with "__"
    # so a panel_id such as "test-->foo" does not produce malformed XML that
    # causes cairosvg/lxml to raise XMLSyntaxError.
    provenance_safe = provenance.replace("--", "__")
    header = _SVG_HEADER_TEMPLATE.format(
        width=width_mm,
        height=height_mm,
        vb_width=vb_w,
        vb_height=vb_h,
        provenance=provenance_safe,
    )
    return header + body + _SVG_FOOTER


# ---------------------------------------------------------------------------
# PDF export (Inkscape / cairosvg fallback)
# ---------------------------------------------------------------------------


def svg_to_pdf(
    svg_path: Path,
    output_pdf: Path,
) -> Path:
    """Convert SVG to PDF.

    Uses Inkscape CLI (high-quality vector conversion) when installed.
    Falls back to cairosvg otherwise.

    Parameters
    ----------
    svg_path:
        Input SVG file path.
    output_pdf:
        Output PDF file path.

    Returns
    -------
    Path
        Output PDF path.

    Raises
    ------
    RuntimeError
        On conversion failure.
    """
    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    inkscape = _find_inkscape()

    if inkscape:
        return _inkscape_to_pdf(inkscape, svg_path, output_pdf)
    else:
        return _cairosvg_to_pdf(svg_path, output_pdf)


def _inkscape_to_pdf(inkscape_bin: str, svg_path: Path, output_pdf: Path) -> Path:
    """Convert SVG to PDF using Inkscape CLI."""
    cmd = [
        inkscape_bin,
        "--export-type=pdf",
        f"--export-filename={output_pdf}",
        str(svg_path),
    ]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode != 0:
            log.warning("Inkscape error: %s", result.stderr[:500])
            # Attempt fallback
            return _cairosvg_to_pdf(svg_path, output_pdf)
        log.info("Inkscape → PDF: %s", output_pdf)
        return output_pdf
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        log.warning("Inkscape execution error (%s) — cairosvg fallback", exc)
        return _cairosvg_to_pdf(svg_path, output_pdf)


def _cairosvg_to_pdf(svg_path: Path, output_pdf: Path) -> Path:
    """Convert SVG to PDF using cairosvg fallback."""
    log.info("cairosvg fallback: %s → %s", svg_path, output_pdf)
    try:
        import cairosvg

        cairosvg.svg2pdf(url=str(svg_path), write_to=str(output_pdf))
        return output_pdf
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            f"SVG → PDF conversion failed (cairosvg): {exc}\n"
            "Install Inkscape (`brew install inkscape`) or verify cairosvg."
        ) from exc


# ---------------------------------------------------------------------------
# Main renderer
# ---------------------------------------------------------------------------


class SchematicRenderer:
    """LLM→SVG schematic renderer (§12.3-②).

    Receives a ``FigureSpec`` schematic panel and:
    1. Searches the ``PrimitiveRegistry`` for primitives matching the panel description.
    2. Parameterizes and combines primitives.
    3. Assembles the SVG string and inserts provenance comments.
    4. Optionally exports to PDF via Inkscape (or cairosvg fallback).

    Parameters
    ----------
    registry:
        Primitive registry. Uses ``default_registry`` when None.
    llm_layout_fn:
        LLM-based layout decision function:
        (query: str, candidates: list[dict]) -> list[tuple[str, dict[str, Any]]]
        Returns (primitive_name, params) pairs. Uses simple first-match when None.
    """

    def __init__(
        self,
        registry: PrimitiveRegistry | None = None,
        llm_layout_fn: Any | None = None,
    ) -> None:
        if registry is None:
            from maglab.figure.primitives.registry import make_default_registry

            registry = make_default_registry()
        self._registry = registry
        self._llm_layout_fn = llm_layout_fn

    def render_panel(
        self,
        panel: PanelSpec,
        *,
        width_mm: float = 89.0,
        height_mm: float = 60.0,
        backend: str = "svg",
        style: str = "nature",
    ) -> str:
        """Render a schematic panel as an SVG string.

        Parameters
        ----------
        panel:
            ``PanelSpec`` (panel_type == SCHEMATIC).
        width_mm:
            SVG width in mm.
        height_mm:
            SVG height in mm.
        backend:
            Render backend.
        style:
            Journal style key.

        Returns
        -------
        str
            Complete SVG XML string.
        """
        # Search primitives using the panel description
        query = panel.extra.get("query", panel.title or "magnetic schematic")
        candidates = self._registry.search(query)

        if not candidates:
            log.warning(
                "[schematic] Panel '%s': no results for '%s' — returning empty SVG",
                panel.panel_id,
                query,
            )
            return self._empty_svg(panel.panel_id, width_mm, height_mm)

        # Determine layout
        primitives_with_params = self._resolve_layout(candidates, panel)

        # Assemble SVG
        svg = assemble_svg(
            primitives_with_params,
            width_mm=width_mm,
            height_mm=height_mm,
            backend=backend,
            style=style,
            provenance=f"panel_id={panel.panel_id}",
        )
        return svg

    def render_to_file(
        self,
        panel: PanelSpec,
        output_path: Path,
        *,
        fmt: str = "svg",
        width_mm: float = 89.0,
        height_mm: float = 60.0,
        style: str = "nature",
    ) -> Path:
        """Render a schematic panel to a file.

        Parameters
        ----------
        panel:
            ``PanelSpec`` (panel_type == SCHEMATIC).
        output_path:
            Output file path.
        fmt:
            Output format — ``"svg"`` or ``"pdf"``.
        width_mm:
            SVG width in mm.
        height_mm:
            SVG height in mm.
        style:
            Journal style key.

        Returns
        -------
        Path
            Path of the saved file.
        """
        svg_string = self.render_panel(
            panel,
            width_mm=width_mm,
            height_mm=height_mm,
            backend="svg",
            style=style,
        )

        output_path.parent.mkdir(parents=True, exist_ok=True)

        if fmt == "svg":
            output_path.write_text(svg_string, encoding="utf-8")
            return output_path

        if fmt == "pdf":
            # Temporary SVG file → PDF conversion
            with tempfile.NamedTemporaryFile(suffix=".svg", delete=False) as tmp:
                tmp_path = Path(tmp.name)
                tmp_path.write_text(svg_string, encoding="utf-8")
            try:
                pdf_path = svg_to_pdf(tmp_path, output_path)
            finally:
                with contextlib.suppress(OSError):
                    tmp_path.unlink()
            return pdf_path

        raise ValueError(f"Unsupported format: '{fmt}'. Use 'svg' or 'pdf'.")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _resolve_layout(
        self,
        candidates: list[dict[str, Any]],
        panel: PanelSpec,
    ) -> list[tuple[Primitive, dict[str, Any]]]:
        """Determine the (Primitive, params) list to place from candidate primitives."""
        # Use LLM layout function if available
        if self._llm_layout_fn is not None:
            try:
                name_params_list = self._llm_layout_fn(
                    panel.extra.get("query", panel.title or ""),
                    candidates,
                )
                result: list[tuple[Primitive, dict[str, Any]]] = []
                for name, params in name_params_list:
                    try:
                        prim = self._registry.load(name)
                        result.append((prim, params))
                    except KeyError:
                        log.warning("[schematic] Primitive '%s' not found", name)
                return result
            except Exception as exc:  # noqa: BLE001
                log.warning("[schematic] llm_layout_fn error: %s — using fallback", exc)

        # Fallback: first candidate + params from panel.extra
        result_fallback: list[tuple[Primitive, dict[str, Any]]] = []
        extra_params = panel.extra.get("params", {}) or {}
        for cand in candidates[:3]:  # up to 3
            try:
                prim = self._registry.load(cand["name"])
                result_fallback.append((prim, dict(extra_params)))
            except KeyError:
                continue
        return result_fallback

    def _empty_svg(
        self,
        panel_id: str,
        width_mm: float,
        height_mm: float,
    ) -> str:
        """Generate an empty SVG (no primitives)."""
        vb_w = width_mm * 3.7795
        vb_h = height_mm * 3.7795
        # XML/SVG comments must not contain "--"; sanitize panel_id so a value
        # such as "test-->foo" does not produce malformed XML.
        safe_panel_id = panel_id.replace("--", "__")
        return (
            f'<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<svg xmlns="http://www.w3.org/2000/svg"'
            f' width="{width_mm}mm" height="{height_mm}mm"'
            f' viewBox="0 0 {vb_w:.1f} {vb_h:.1f}">\n'
            f"  <!-- Generated by MagLab schematic.py — panel_id={safe_panel_id} -->\n"
            f'  <text x="50%" y="50%" text-anchor="middle" font-size="12">'
            f"[schematic — no primitives]</text>\n"
            f"</svg>\n"
        )
